app:
    resource: "@AppBundle/Controller/"
    type:     annotation
login:
    pattern:   /login
    defaults:  { _controller: AppBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout
Sisaf:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /administrar