role:
    pattern:  /
    defaults: { _controller: "AppBundle:role:index" }

role_show:
    pattern:  /{id}/show
    defaults: { _controller: "AppBundle:role:show" }

role_new:
    pattern:  /new
    defaults: { _controller: "AppBundle:role:new" }

role_create:
    pattern:  /create
    defaults: { _controller: "AppBundle:role:create" }
    requirements: { _method: post }

role_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "AppBundle:role:edit" }

role_update:
    pattern:  /{id}/update
    defaults: { _controller: "AppBundle:role:update" }
    requirements: { _method: post }

role_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "AppBundle:role:delete" }
    requirements: { _method: post }
