AppBundle\Entity\Usuario:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: '25'
        password:
            type: string
            length: '125'
        email:
            type: string
            length: '60'        
        telefono:
            type: string
            length: '13'
        salt:
            type: string
            length: '125'
    manyToMany:
        roles:
            targetEntity: AppBundle\Entity\role
            joinTable:
                name: user_role
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    role_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
